commandOpenSeller:
  - "b"
  - "sell"
  - "aseller"

# Сообщение об получение денег
messageSale: "&fВы получили &e%seller_pay%&f$"
# Сообщение если в скупщике нет предметов для продажи
messageItemsDeficit: "&fУ вас нет предметов для продажи"
#########################[Скупщик]#######################
sellerMenu: seller
#######################[Авто-скупка]#####################
loreAction:
  - " "
  - "Товар продаётся автоматически"
  - "Обычная цена: %default_prise%"
  - "Текущая цена: %now_prise%"
loreNoAction:
  - " "
  - "Товар не продаётся автоматически"
  - "Обычная цена: %default_prise%"
  - "Текущая цена: %now_prise%"
menu:
  seller:
    path: Menu/seller.yml
  category:
    path: Menu/category.yml
  mobs:
    path: Menu/mobs.yml
  mine:
    path: Menu/mine.yml
