# Ищем дюпы

# Название кнопки продажи
display_button_sell: " "

# Описание кнопки продажи
lore_button_sell:
  - '&fНажмите чтобы сдать все предметы'
  - '&fПредметов на сумму: &e%seller_pay%'

# Позиция кнопки продажи
position_button_sell: 49

# Какие слоты будут использоваться для добавления предметов
activeSlots:
  - 0-44

# Какие слоты не будут использоваться
noActiveSlots:
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
# Предмет и его цена
priseItem:
  STONE: 50.0
  DIAMOND: 100.0

# Сообщение об получение денег
messageSale: "&fВы получили &e%seller_pay%&f$"
# Сообщение если в скупщике нет предметов для продажи
messageItemsDeficit: "&fУ вас нет предметов для продажи"