# Версия бета-0.1.2-beta


commandOpenSeller:
  - "b"
  - "sell"
  - "aseller"


#########################[Скупщик]#######################
# укажите название для меню скупки
sellerMenu: "seller"

menu:
  seller:
    path: Menu/seller.yml
  category:
    path: Menu/category.yml
  mobs:
    path: Menu/mobs.yml
  mine:
    path: Menu/mine.yml

# в данный момент все что написано ниже не работает
#######################[Авто-скупка]#####################
loreAction:
  - " "
  - "Товар продаётся автоматически"
  - "Обычная цена: %default_prise%"
  - "Текущая цена: %now_prise%"
loreNoAction:
  - " "
  - "Товар не продаётся автоматически"
  - "Обычная цена: %default_prise%"
  - "Текущая цена: %now_prise%"

