# Ищем дюпы

# Название кнопки продажи
display_button_sell: " "

# Описание кнопки продажи
lore_button_sell:
  - '&fНажмите чтобы сдать все предметы'
  - '&fПредметов на сумму: &e%seller_pay%'

# Позиция кнопки продажи
position_button_sell: 49

# Предмет и его цена
priseItem:
  STONE: 50.0
  DIAMOND: 100.0

# Сообщение об получение денег
messageSale: "&fВы получили &e%seller_pay%&f$"
# Сообщение если в скупщике нет предметов для продажи
messageItemsDeficit: "&fУ вас нет предметов для продажи"